<?php
$cars = [
    [
        'brand' => 'Volvo',
        'model' => 'S80',
        'seats' => 5,
        'color' => 'Grey',
        'year' => 2002,
        'brand_country' => 'Sweden',
    ],
    [
        'brand' => 'Audi',
        'model' => 'TT',
        'seats' => 2,
        'color' => 'Red',
        'year' => 2007,
        'brand_country' => 'Germany',
    ],
    [
        'brand' => 'Volkswagen',
        'model' => 'Golf Mk2',
        'seats' => 4,
        'color' => 'Blue',
        'year' => 2004,
        'brand_country' => 'Germany',
    ],
    [
        'brand' => 'Ford',
        'model' => 'Focus',
        'seats' => 5,
        'color' => 'White',
        'year' => 2015,
        'brand_country' => 'USA',
    ],
    [
        'brand' => 'BMW',
        'model' => '320D',
        'seats' => 5,
        'color' => 'Grey',
        'year' => 2010,
        'brand_country' => 'Germany',
    ],
    [
        'brand' => 'Renault',
        'model' => 'Megane',
        'seats' => 5,
        'color' => 'Blue',
        'year' => 2009,
        'brand_country' => 'France',
    ],
];
